version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/database   # Hier wird das Verzeichnis der SQLite-Datenbank gemountet
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: python:3.9-slim
    command: tail -f /dev/null   # Hält den Container ausgeführt, damit er als Datenbank verwendet werden kann
    volumes:
      - ./database:/app/database   # Mountet das Verzeichnis der SQLite-Datenbank
