apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
        - name: web
          image: nicbodibm/m300mitdb:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  selector:
    app: my-flask-app
  ports:
    - port: 80  # Externer Port, über den der Service erreichbar sein wird
      targetPort: 5000  # Interner Port, auf den der Service verweist
